BEGIN;

DROP TABLE IF EXISTS ep.regard CASCADE;

CREATE TABLE ep.regard (
    fid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    geom geometry(PointZ, 26191),
    ep_agent varchar(400),
    ep_sect_com varchar(400),
    ep_statut varchar(400),
    ep_adresse varchar(400),
    ep_agent_crea varchar(400),
    sec_com varchar(400),
    sect_hydr varchar(400),
    zone varchar(400),
    uuid uuid,
    z_radier varchar(400),
    z_surf varchar(400),
    ep_date_insertion date,
    ep_coor_x double precision,
    ep_coor_y double precision,
    ep_coor_z double precision,
    id_commune integer,
    id_province integer,
    id_user_creat integer,
    id_user_modif integer,
    date_creation timestamp without time zone,
    date_modif timestamp without time zone,
    is_deleted boolean DEFAULT false,
    is_validated boolean DEFAULT false,
    id_user_valid integer,
    date_validation timestamp without time zone,
    ep_section varchar(254),
    emplacement varchar(254),
    ep_tampon varchar(254),
    ep_ref_rue varchar(400),
    ep_conf_plan varchar(400),
    ep_observation varchar(400),
    ep_anomalie boolean DEFAULT false,
    mode_localisation varchar(400),
    echelon varchar(400),
    anomalie_tamp varchar(400),
    anomalie_regard varchar(400),
    "GENRATRICE_SUP" double precision,
    ep_profondeur double precision,
    photo_1 text,
    photo_2 text,
    photo_3 text,
    photo_4 text,
    CONSTRAINT regard_ep_statut_chk CHECK (
        ep_statut IS NULL OR
        ep_statut IN (
            'EP_POSE', 'EP_REHABILITE', 'EP_EXISTANT', 'EP_PROJETE',
            'EP_A REHABI', 'EP_EN COURSS', 'EP_A RESILISE'
        )
    ),
    CONSTRAINT regard_emplacement_chk CHECK (
        emplacement IS NULL OR
        emplacement IN (
            'S-TROTTOIR', 'S-CHAUSSEE', 'S-TROTOIR C-CHAISSI',
            'TN', 'PISTE', 'TERRE_AGRICOLE'
        )
    ),
    CONSTRAINT regard_tampon_chk CHECK (
        ep_tampon IS NULL OR
        ep_tampon IN ('FD400', 'FD250', 'Béton')
    ),
    CONSTRAINT regard_conf_plan_chk CHECK (
        ep_conf_plan IS NULL OR
        ep_conf_plan IN (
            'Conforme aux plan',
            'Objet découvrt sur terrain',
            'Objet non trouvé sur le terrain'
        )
    ),
    CONSTRAINT regard_mode_localisation_chk CHECK (
        mode_localisation IS NULL OR
        mode_localisation IN (
            'Levé topographique',
            'Triangulé',
            'Schématique',
            'Indéterminé'
        )
    ),
    CONSTRAINT regard_echelon_chk CHECK (
        echelon IS NULL OR echelon IN ('O', 'N')
    ),
    CONSTRAINT regard_anomalie_tamp_chk CHECK (
        anomalie_tamp IS NULL OR
        anomalie_tamp IN (
            'Tampons en mauvais état',
            'Tampons Manquant',
            'Tampons Scellés'
        )
    ),
    CONSTRAINT regard_anomalie_regard_chk CHECK (
        anomalie_regard IS NULL OR
        anomalie_regard IN (
            'A mettre à la cote',
            'Inaccessible',
            'Ouvrage dégradés',
            'Regards Enterrés',
            'Regards Noyés',
            'Regards à curer',
            'Sectionnement enterré',
            'Autre'
        )
    )
);

COMMENT ON TABLE ep.regard IS 'Table SRM point pour les regards EP.';

CREATE UNIQUE INDEX regard_uuid_uidx
    ON ep.regard (uuid)
    WHERE uuid IS NOT NULL;

CREATE INDEX regard_geom_gix
    ON ep.regard
    USING gist (geom);

CREATE INDEX regard_id_commune_idx
    ON ep.regard (id_commune);

CREATE INDEX regard_id_province_idx
    ON ep.regard (id_province);

CREATE INDEX regard_date_creation_idx
    ON ep.regard (date_creation DESC);

CREATE INDEX regard_is_deleted_idx
    ON ep.regard (is_deleted);

DELETE FROM public.srm_field_option
WHERE table_schema = 'ep'
  AND table_name = 'regard';

INSERT INTO public.srm_field_option (
    table_schema,
    table_name,
    field_name,
    code_value,
    label_value,
    display_order
)
SELECT
    table_schema,
    'regard',
    field_name,
    code_value,
    label_value,
    display_order
FROM public.srm_field_option
WHERE table_schema = 'ep'
  AND table_name = 'regard_ep';

CREATE OR REPLACE FUNCTION public.touch_regard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.date_creation IS NULL THEN
            NEW.date_creation := NOW();
        END IF;

        IF NEW.date_modif IS NULL THEN
            NEW.date_modif := NEW.date_creation;
        END IF;

        IF NEW.ep_date_insertion IS NULL AND NEW.date_creation IS NOT NULL THEN
            NEW.ep_date_insertion := NEW.date_creation::date;
        END IF;
    ELSE
        NEW.date_modif := NOW();

        IF NEW.ep_date_insertion IS NULL AND NEW.date_creation IS NOT NULL THEN
            NEW.ep_date_insertion := NEW.date_creation::date;
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_touch_regard
BEFORE INSERT OR UPDATE
ON ep.regard
FOR EACH ROW
EXECUTE FUNCTION public.touch_regard();

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_proc p
        JOIN pg_namespace n
          ON n.oid = p.pronamespace
        WHERE n.nspname = 'public'
          AND p.proname = 'capture_historique_attribut'
    ) THEN
        EXECUTE 'CREATE TRIGGER trg_audit_regard AFTER INSERT OR UPDATE OR DELETE ON ep.regard FOR EACH ROW EXECUTE FUNCTION public.capture_historique_attribut(''fid'')';
    END IF;
END;
$$;

COMMIT;
