BEGIN;

CREATE OR REPLACE FUNCTION public.regard_miroir_square_size_m()
RETURNS double precision
LANGUAGE sql
AS $$
    SELECT 24.0::double precision
$$;

ALTER TABLE IF EXISTS ep.regard
    ADD COLUMN IF NOT EXISTS photo_1 text,
    ADD COLUMN IF NOT EXISTS photo_2 text,
    ADD COLUMN IF NOT EXISTS photo_3 text,
    ADD COLUMN IF NOT EXISTS photo_4 text;

DROP TABLE IF EXISTS ep.regard_miroir CASCADE;

CREATE TABLE ep.regard_miroir (
    fid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fid_regard_source integer NOT NULL UNIQUE,
    geom geometry(PolygonZ, 26191),
    ep_agent varchar(400),
    ep_sect_com varchar(400),
    ep_statut varchar(400),
    ep_adresse varchar(400),
    ep_agent_crea varchar(400),
    sec_com varchar(400),
    sect_hydr varchar(400),
    zone varchar(400),
    uuid uuid,
    z_radier varchar(400),
    z_surf varchar(400),
    ep_date_insertion date,
    ep_coor_x double precision,
    ep_coor_y double precision,
    ep_coor_z double precision,
    id_commune integer,
    id_province integer,
    id_user_creat integer,
    id_user_modif integer,
    date_creation timestamp without time zone,
    date_modif timestamp without time zone,
    is_deleted boolean DEFAULT false,
    is_validated boolean DEFAULT false,
    id_user_valid integer,
    date_validation timestamp without time zone,
    ep_section varchar(254),
    emplacement varchar(254),
    ep_tampon varchar(254),
    ep_ref_rue varchar(400),
    ep_conf_plan varchar(400),
    ep_observation varchar(400),
    ep_anomalie boolean DEFAULT false,
    mode_localisation varchar(400),
    echelon varchar(400),
    anomalie_tamp varchar(400),
    anomalie_regard varchar(400),
    "GENRATRICE_SUP" double precision,
    ep_profondeur double precision,
    photo_1 text,
    photo_2 text,
    photo_3 text,
    photo_4 text,
    CONSTRAINT regard_miroir_statut_chk CHECK (
        ep_statut IS NULL OR
        ep_statut IN (
            'EP_POSE', 'EP_REHABILITE', 'EP_EXISTANT', 'EP_PROJETE',
            'EP_A REHABI', 'EP_EN COURSS', 'EP_A RESILISE'
        )
    ),
    CONSTRAINT regard_miroir_emplacement_chk CHECK (
        emplacement IS NULL OR
        emplacement IN (
            'S-TROTTOIR', 'S-CHAUSSEE', 'S-TROTOIR C-CHAISSI',
            'TN', 'PISTE', 'TERRE_AGRICOLE'
        )
    ),
    CONSTRAINT regard_miroir_tampon_chk CHECK (
        ep_tampon IS NULL OR
        ep_tampon IN ('FD400', 'FD250', 'Béton')
    ),
    CONSTRAINT regard_miroir_conf_plan_chk CHECK (
        ep_conf_plan IS NULL OR
        ep_conf_plan IN (
            'Conforme aux plan',
            'Objet découvrt sur terrain',
            'Objet non trouvé sur le terrain'
        )
    ),
    CONSTRAINT regard_miroir_mode_localisation_chk CHECK (
        mode_localisation IS NULL OR
        mode_localisation IN (
            'Levé topographique',
            'Triangulé',
            'Schématique',
            'Indéterminé',
            'Dessin',
            'Géo-radar'
        )
    ),
    CONSTRAINT regard_miroir_echelon_chk CHECK (
        echelon IS NULL OR echelon IN ('O', 'N')
    ),
    CONSTRAINT regard_miroir_anomalie_tamp_chk CHECK (
        anomalie_tamp IS NULL OR
        anomalie_tamp IN (
            'Tampons en mauvais état',
            'Tampons Manquant',
            'Tampons Scellés'
        )
    ),
    CONSTRAINT regard_miroir_anomalie_regard_chk CHECK (
        anomalie_regard IS NULL OR
        anomalie_regard IN (
            'A mettre à la cote',
            'Inaccessible',
            'Ouvrage dégradés',
            'Regards Enterrés',
            'Regards Noyés',
            'Regards à curer',
            'Sectionnement enterré',
            'Autre'
        )
    )
);

COMMENT ON TABLE ep.regard_miroir IS
'Table miroir dérivée de ep.regard avec géométrie carrée 24x24 m (paramétrable).';

CREATE UNIQUE INDEX regard_miroir_uuid_uidx
    ON ep.regard_miroir (uuid)
    WHERE uuid IS NOT NULL;

CREATE INDEX regard_miroir_geom_gix
    ON ep.regard_miroir
    USING gist (geom);

CREATE INDEX regard_miroir_fid_regard_source_idx
    ON ep.regard_miroir (fid_regard_source);

CREATE OR REPLACE FUNCTION public.build_regard_miroir_geom(
    source_geom geometry
)
RETURNS geometry
LANGUAGE plpgsql
AS $$
DECLARE
    half_size double precision := public.regard_miroir_square_size_m() / 2.0;
    srid_value integer := COALESCE(ST_SRID(source_geom), 26191);
    x double precision;
    y double precision;
    z double precision;
BEGIN
    IF source_geom IS NULL OR ST_IsEmpty(source_geom) THEN
        RETURN NULL;
    END IF;

    x := ST_X(source_geom);
    y := ST_Y(source_geom);
    z := COALESCE(ST_Z(source_geom), 0.0);

    RETURN ST_SetSRID(
        ST_MakePolygon(
            ST_MakeLine(ARRAY[
                ST_MakePoint(x - half_size, y - half_size, z),
                ST_MakePoint(x + half_size, y - half_size, z),
                ST_MakePoint(x + half_size, y + half_size, z),
                ST_MakePoint(x - half_size, y + half_size, z),
                ST_MakePoint(x - half_size, y - half_size, z)
            ])
        ),
        srid_value
    )::geometry(PolygonZ, 26191);
END;
$$;

CREATE OR REPLACE FUNCTION public.sync_regard_miroir_from_regard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        DELETE FROM ep.regard_miroir
        WHERE fid_regard_source = OLD.fid;
        RETURN OLD;
    END IF;

    INSERT INTO ep.regard_miroir (
        fid_regard_source,
        geom,
        ep_agent,
        ep_sect_com,
        ep_statut,
        ep_adresse,
        ep_agent_crea,
        sec_com,
        sect_hydr,
        zone,
        uuid,
        z_radier,
        z_surf,
        ep_date_insertion,
        ep_coor_x,
        ep_coor_y,
        ep_coor_z,
        id_commune,
        id_province,
        id_user_creat,
        id_user_modif,
        date_creation,
        date_modif,
        is_deleted,
        is_validated,
        id_user_valid,
        date_validation,
        ep_section,
        emplacement,
        ep_tampon,
        ep_ref_rue,
        ep_conf_plan,
        ep_observation,
        ep_anomalie,
        mode_localisation,
        echelon,
        anomalie_tamp,
        anomalie_regard,
        "GENRATRICE_SUP",
        ep_profondeur,
        photo_1,
        photo_2,
        photo_3,
        photo_4
    )
    VALUES (
        NEW.fid,
        public.build_regard_miroir_geom(
            CASE
                WHEN NEW.geom IS NOT NULL AND NOT ST_IsEmpty(NEW.geom)
                    THEN NEW.geom
                WHEN NEW.ep_coor_x IS NOT NULL AND NEW.ep_coor_y IS NOT NULL
                    THEN ST_SetSRID(
                        ST_MakePoint(
                            NEW.ep_coor_x,
                            NEW.ep_coor_y,
                            COALESCE(NEW.ep_coor_z, 0.0)
                        ),
                        26191
                    )
                ELSE NULL
            END
        ),
        NEW.ep_agent,
        NEW.ep_sect_com,
        NEW.ep_statut,
        NEW.ep_adresse,
        NEW.ep_agent_crea,
        NEW.sec_com,
        NEW.sect_hydr,
        NEW.zone,
        NEW.uuid,
        NEW.z_radier,
        NEW.z_surf,
        NEW.ep_date_insertion,
        NEW.ep_coor_x,
        NEW.ep_coor_y,
        NEW.ep_coor_z,
        NEW.id_commune,
        NEW.id_province,
        NEW.id_user_creat,
        NEW.id_user_modif,
        NEW.date_creation,
        NEW.date_modif,
        NEW.is_deleted,
        NEW.is_validated,
        NEW.id_user_valid,
        NEW.date_validation,
        NEW.ep_section,
        NEW.emplacement,
        NEW.ep_tampon,
        NEW.ep_ref_rue,
        NEW.ep_conf_plan,
        NEW.ep_observation,
        NEW.ep_anomalie,
        NEW.mode_localisation,
        NEW.echelon,
        NEW.anomalie_tamp,
        NEW.anomalie_regard,
        NEW."GENRATRICE_SUP",
        NEW.ep_profondeur,
        NEW.photo_1,
        NEW.photo_2,
        NEW.photo_3,
        NEW.photo_4
    )
    ON CONFLICT (fid_regard_source) DO UPDATE SET
        geom = EXCLUDED.geom,
        ep_agent = EXCLUDED.ep_agent,
        ep_sect_com = EXCLUDED.ep_sect_com,
        ep_statut = EXCLUDED.ep_statut,
        ep_adresse = EXCLUDED.ep_adresse,
        ep_agent_crea = EXCLUDED.ep_agent_crea,
        sec_com = EXCLUDED.sec_com,
        sect_hydr = EXCLUDED.sect_hydr,
        zone = EXCLUDED.zone,
        uuid = EXCLUDED.uuid,
        z_radier = EXCLUDED.z_radier,
        z_surf = EXCLUDED.z_surf,
        ep_date_insertion = EXCLUDED.ep_date_insertion,
        ep_coor_x = EXCLUDED.ep_coor_x,
        ep_coor_y = EXCLUDED.ep_coor_y,
        ep_coor_z = EXCLUDED.ep_coor_z,
        id_commune = EXCLUDED.id_commune,
        id_province = EXCLUDED.id_province,
        id_user_creat = EXCLUDED.id_user_creat,
        id_user_modif = EXCLUDED.id_user_modif,
        date_creation = EXCLUDED.date_creation,
        date_modif = EXCLUDED.date_modif,
        is_deleted = EXCLUDED.is_deleted,
        is_validated = EXCLUDED.is_validated,
        id_user_valid = EXCLUDED.id_user_valid,
        date_validation = EXCLUDED.date_validation,
        ep_section = EXCLUDED.ep_section,
        emplacement = EXCLUDED.emplacement,
        ep_tampon = EXCLUDED.ep_tampon,
        ep_ref_rue = EXCLUDED.ep_ref_rue,
        ep_conf_plan = EXCLUDED.ep_conf_plan,
        ep_observation = EXCLUDED.ep_observation,
        ep_anomalie = EXCLUDED.ep_anomalie,
        mode_localisation = EXCLUDED.mode_localisation,
        echelon = EXCLUDED.echelon,
        anomalie_tamp = EXCLUDED.anomalie_tamp,
        anomalie_regard = EXCLUDED.anomalie_regard,
        "GENRATRICE_SUP" = EXCLUDED."GENRATRICE_SUP",
        ep_profondeur = EXCLUDED.ep_profondeur,
        photo_1 = EXCLUDED.photo_1,
        photo_2 = EXCLUDED.photo_2,
        photo_3 = EXCLUDED.photo_3,
        photo_4 = EXCLUDED.photo_4;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_sync_regard_miroir ON ep.regard;
CREATE TRIGGER trg_sync_regard_miroir
AFTER INSERT OR UPDATE OR DELETE
ON ep.regard
FOR EACH ROW
EXECUTE FUNCTION public.sync_regard_miroir_from_regard();

INSERT INTO ep.regard_miroir (
    fid_regard_source,
    geom,
    ep_agent,
    ep_sect_com,
    ep_statut,
    ep_adresse,
    ep_agent_crea,
    sec_com,
    sect_hydr,
    zone,
    uuid,
    z_radier,
    z_surf,
    ep_date_insertion,
    ep_coor_x,
    ep_coor_y,
    ep_coor_z,
    id_commune,
    id_province,
    id_user_creat,
    id_user_modif,
    date_creation,
    date_modif,
    is_deleted,
    is_validated,
    id_user_valid,
    date_validation,
    ep_section,
    emplacement,
    ep_tampon,
    ep_ref_rue,
    ep_conf_plan,
    ep_observation,
    ep_anomalie,
    mode_localisation,
    echelon,
    anomalie_tamp,
    anomalie_regard,
    "GENRATRICE_SUP",
    ep_profondeur,
    photo_1,
    photo_2,
    photo_3,
    photo_4
)
SELECT
    r.fid,
    public.build_regard_miroir_geom(
        CASE
            WHEN r.geom IS NOT NULL AND NOT ST_IsEmpty(r.geom)
                THEN r.geom
            WHEN r.ep_coor_x IS NOT NULL AND r.ep_coor_y IS NOT NULL
                THEN ST_SetSRID(
                    ST_MakePoint(
                        r.ep_coor_x,
                        r.ep_coor_y,
                        COALESCE(r.ep_coor_z, 0.0)
                    ),
                    26191
                )
            ELSE NULL
        END
    ),
    r.ep_agent,
    r.ep_sect_com,
    r.ep_statut,
    r.ep_adresse,
    r.ep_agent_crea,
    r.sec_com,
    r.sect_hydr,
    r.zone,
    r.uuid,
    r.z_radier,
    r.z_surf,
    r.ep_date_insertion,
    r.ep_coor_x,
    r.ep_coor_y,
    r.ep_coor_z,
    r.id_commune,
    r.id_province,
    r.id_user_creat,
    r.id_user_modif,
    r.date_creation,
    r.date_modif,
    r.is_deleted,
    r.is_validated,
    r.id_user_valid,
    r.date_validation,
    r.ep_section,
    r.emplacement,
    r.ep_tampon,
    r.ep_ref_rue,
    r.ep_conf_plan,
    r.ep_observation,
    r.ep_anomalie,
    r.mode_localisation,
    r.echelon,
    r.anomalie_tamp,
    r.anomalie_regard,
    r."GENRATRICE_SUP",
    r.ep_profondeur,
    r.photo_1,
    r.photo_2,
    r.photo_3,
    r.photo_4
FROM ep.regard AS r
ON CONFLICT (fid_regard_source) DO UPDATE SET
    geom = EXCLUDED.geom,
    ep_agent = EXCLUDED.ep_agent,
    ep_sect_com = EXCLUDED.ep_sect_com,
    ep_statut = EXCLUDED.ep_statut,
    ep_adresse = EXCLUDED.ep_adresse,
    ep_agent_crea = EXCLUDED.ep_agent_crea,
    sec_com = EXCLUDED.sec_com,
    sect_hydr = EXCLUDED.sect_hydr,
    zone = EXCLUDED.zone,
    uuid = EXCLUDED.uuid,
    z_radier = EXCLUDED.z_radier,
    z_surf = EXCLUDED.z_surf,
    ep_date_insertion = EXCLUDED.ep_date_insertion,
    ep_coor_x = EXCLUDED.ep_coor_x,
    ep_coor_y = EXCLUDED.ep_coor_y,
    ep_coor_z = EXCLUDED.ep_coor_z,
    id_commune = EXCLUDED.id_commune,
    id_province = EXCLUDED.id_province,
    id_user_creat = EXCLUDED.id_user_creat,
    id_user_modif = EXCLUDED.id_user_modif,
    date_creation = EXCLUDED.date_creation,
    date_modif = EXCLUDED.date_modif,
    is_deleted = EXCLUDED.is_deleted,
    is_validated = EXCLUDED.is_validated,
    id_user_valid = EXCLUDED.id_user_valid,
    date_validation = EXCLUDED.date_validation,
    ep_section = EXCLUDED.ep_section,
    emplacement = EXCLUDED.emplacement,
    ep_tampon = EXCLUDED.ep_tampon,
    ep_ref_rue = EXCLUDED.ep_ref_rue,
    ep_conf_plan = EXCLUDED.ep_conf_plan,
    ep_observation = EXCLUDED.ep_observation,
    ep_anomalie = EXCLUDED.ep_anomalie,
    mode_localisation = EXCLUDED.mode_localisation,
    echelon = EXCLUDED.echelon,
    anomalie_tamp = EXCLUDED.anomalie_tamp,
    anomalie_regard = EXCLUDED.anomalie_regard,
    "GENRATRICE_SUP" = EXCLUDED."GENRATRICE_SUP",
    ep_profondeur = EXCLUDED.ep_profondeur,
    photo_1 = EXCLUDED.photo_1,
    photo_2 = EXCLUDED.photo_2,
    photo_3 = EXCLUDED.photo_3,
    photo_4 = EXCLUDED.photo_4;

COMMIT;
