# Generated by Django 5.2.5 on 2025-08-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('prenom', models.TextField()),
                ('mail', models.TextField(unique=True)),
                ('mdp', models.TextField()),
                ('role', models.TextField()),
            ],
        ),
    ]
