# Generated by Django 6.0.1 on 2026-02-01 16:31

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chaussees_enquetepolygone_pointscoupures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piste',
            name='communes_rurales_id',
            field=models.ForeignKey(blank=True, db_column='communes_rurales_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.communerurale'),
        ),
        migrations.AddField(
            model_name='piste',
            name='cout_investissement',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piste',
            name='debut_travaux',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piste',
            name='fin_travaux',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piste',
            name='financement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piste',
            name='fonctionnalite',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piste',
            name='interet_socio_administratif',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piste',
            name='login_id',
            field=models.ForeignKey(blank=True, db_column='login_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.login'),
        ),
        migrations.AddField(
            model_name='piste',
            name='niveau_service',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piste',
            name='note_globale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piste',
            name='plateforme',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piste',
            name='population_desservie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piste',
            name='potentiel_agricole',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piste',
            name='projet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piste',
            name='protection_environnement',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piste',
            name='relief',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piste',
            name='vegetation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='piste',
            name='code_piste',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='piste',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='piste',
            name='frequence_trafic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='piste',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='piste',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='piste',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='piste',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
