from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_drop_basemap_package_state'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelTable(
                    name='epbornefontaine',
                    table='"ep"."ep_bf"',
                ),
                migrations.AlterModelTable(
                    name='epbouchecles',
                    table='"ep"."bouche_a_cles"',
                ),
                migrations.AlterModelTable(
                    name='epbouchedarrosage',
                    table='"ep"."ep_bouche_arro"',
                ),
                migrations.AlterModelTable(
                    name='epbranchement',
                    table='"ep"."ep_branchement"',
                ),
                migrations.AlterModelTable(
                    name='epcompteurabonne',
                    table='"ep"."ep_compteur_i"',
                ),
                migrations.AlterModelTable(
                    name='epconduitebureau',
                    table='"ep"."ep_conduite"',
                ),
                migrations.AlterModelTable(
                    name='epconduiteterrain',
                    table='"ep"."conduite_terrain"',
                ),
                migrations.AlterModelTable(
                    name='epconedereduction',
                    table='"ep"."ep_cone_reduc"',
                ),
                migrations.AlterModelTable(
                    name='epforage',
                    table='"ep"."ep_forage"',
                ),
                migrations.AlterModelTable(
                    name='ephydrant',
                    table='"ep"."ep_hydrant"',
                ),
                migrations.AlterModelTable(
                    name='epnoeud',
                    table='"ep"."ep_noeud"',
                ),
                migrations.AlterModelTable(
                    name='epobturateur',
                    table='"ep"."ep_obturateur"',
                ),
                migrations.AlterModelTable(
                    name='eppompe',
                    table='"ep"."ep_pompe"',
                ),
                migrations.AlterModelTable(
                    name='eppuit',
                    table='"ep"."ep_puit"',
                ),
                migrations.AlterModelTable(
                    name='epreducteurdepression',
                    table='"ep"."ep_reduc_pres"',
                ),
                migrations.AlterModelTable(
                    name='epregard',
                    table='"ep"."ep_regard_point"',
                ),
                migrations.AlterModelTable(
                    name='epregardmiroir',
                    table='"ep"."ep_regard"',
                ),
                migrations.AlterModelTable(
                    name='epreservoir',
                    table='"ep"."ep_reservoir"',
                ),
                migrations.AlterModelTable(
                    name='epstationdepompage',
                    table='"ep"."ep_station_pompage"',
                ),
                migrations.AlterModelTable(
                    name='eptraverse',
                    table='"ep"."ep_traversee"',
                ),
                migrations.AlterModelTable(
                    name='epvanne',
                    table='"ep"."ep_vanne"',
                ),
                migrations.AlterModelTable(
                    name='epvannedevidange',
                    table='"ep"."ep_vidange"',
                ),
                migrations.AlterModelTable(
                    name='epventouse',
                    table='"ep"."ep_ventouse"',
                ),
            ],
        ),
    ]
